// Downloads the three web fonts the design system names and writes
// `src/styles/fonts.css` pointing at local copies.
//
// Why self-hosted rather than the Google Fonts CDN (11-build-plan.md S40,
// 06-frontend-architecture.md §8): no third-party request on page load, the
// container image builds and runs offline, and Vazirmatn ships only the
// subsets a Persian reader actually needs instead of its whole face.
//
// Run from `frontend/`:  node scripts/fetch-fonts.mjs
// The downloaded .woff2 files are committed — a build must not need the network.

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const OUT_DIR = path.resolve(import.meta.dirname, '../public/assets/fonts')
const CSS_PATH = path.resolve(import.meta.dirname, '../src/styles/fonts.css')

// A modern UA, so the API answers with woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

/**
 * `subsets` filters the `/* latin *\/`-style comments Google emits before each
 * @font-face. Latin-only for the two Latin faces; Vazirmatn carries `arabic`
 * *and* `latin` because a Persian page still renders ASCII digits, product
 * names and invite codes.
 */
const FAMILIES = [
  { family: 'Outfit', weights: [400, 500, 600, 700], subsets: ['latin'] },
  { family: 'DM Sans', weights: [400, 500, 700], subsets: ['latin'] },
  { family: 'Vazirmatn', weights: [400, 500, 600, 700], subsets: ['arabic', 'latin'] },
]

/** Parses Google's CSS into `{ subset, weight, url, unicodeRange }` records. */
function parseFaces(css) {
  const faces = []
  // Each block is preceded by a `/* subset */` comment naming its unicode range.
  const blocks = css.split('/*').slice(1)

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim()
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1]
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (weight && url && unicodeRange) {
      faces.push({ subset, weight: Number(weight), url, unicodeRange })
    }
  }
  return faces
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true })

  const rules = [
    '/* AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Self-hosted so no page load reaches a third party and the container',
    ' * builds offline. `font-display: swap` and the real fallback stacks in',
    ' * tokens.css mean text is readable before these arrive.',
    ' *',
    ' * Outfit and DM Sans: SIL Open Font License 1.1.',
    ' * Vazirmatn: SIL Open Font License 1.1.',
    ' */',
    '',
  ]

  for (const { family, weights, subsets } of FAMILIES) {
    const spec = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`
    const res = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
      headers: { 'User-Agent': UA },
    })
    if (!res.ok) throw new Error(`${family}: CSS request failed with ${res.status}`)

    const faces = parseFaces(await res.text()).filter((f) => subsets.includes(f.subset))
    if (faces.length === 0) throw new Error(`${family}: no faces matched ${subsets.join(', ')}`)

    const slug = family.toLowerCase().replace(/ /g, '-')

    for (const face of faces) {
      const file = `${slug}-${face.weight}-${face.subset}.woff2`
      const bin = await fetch(face.url, { headers: { 'User-Agent': UA } })
      if (!bin.ok) throw new Error(`${file}: download failed with ${bin.status}`)

      await writeFile(path.join(OUT_DIR, file), Buffer.from(await bin.arrayBuffer()))

      // Quote only what CSS requires quoting — a bare multi-word family name is
      // invalid, a quoted single-word one trips stylelint's font-family-name-quotes.
      const name = family.includes(' ') ? `"${family}"` : family

      rules.push(
        '@font-face {',
        `  font-family: ${name};`,
        '  font-style: normal;',
        `  font-weight: ${face.weight};`,
        '  font-display: swap;',
        `  src: url('/assets/fonts/${file}') format('woff2');`,
        `  unicode-range: ${face.unicodeRange};`,
        '}',
        '',
      )
      console.log(`  ${file}`)
    }
  }

  await writeFile(CSS_PATH, rules.join('\n'))
  console.log(`\nWrote ${path.relative(process.cwd(), CSS_PATH)}`)
}

await main()
